import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const pluginDirectory = dirname(fileURLToPath(import.meta.url));
const sources = ['brand-and-flows.js', 'wireframe-content.js', 'wireframes.js'];
const banner = '// Generated by scripts/figma-plugin/build.mjs. Edit the source files, then rebuild.\n\n';
const output = sources.map((file) => readFileSync(join(pluginDirectory, file), 'utf8').trimEnd()).join('\n\n');

writeFileSync(join(pluginDirectory, 'code.js'), `${banner}${output}\n`, 'utf8');
console.log(`Built code.js from ${sources.join(' + ')}`);
